### ISSUE TITLE
Game doesnotlaunch/crashes on initialization when mod Bclib is installed

### ISSUE THREAD

**Issue by Hunterghost92** [huskcasaca/effortless#163]
I get this error    

 java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'bclib'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$eki000$notenoughcrashes$catchFabricInit(class_310.java:25172)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at org.betterx.betternether.client.BetterNetherClient.registerRenderLayers(BetterNetherClient.java:27)
		at org.betterx.betternether.client.BetterNetherClient.onInitializeClient(BetterNetherClient.java:19)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 8 more

**Comment by Hunterghost92** [comment]
Restarting the system 3 times somehow fixed it
