### ISSUE TITLE
Server does not launch with the newest 1.21 version

### ISSUE THREAD

**Issue by d4w1kpl** [huskcasaca/effortless#164]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'effortless'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
	at dev.huskuraft.effortless.fabric.events.FabricEventRegistry.lambda$new$0(FabricEventRegistry.java:20) ~[effortless-1.21-3.1.0.jar:?]
	at dev.huskuraft.effortless.fabric.events.common.PlatformLifecycleEvents.lambda$static$0(PlatformLifecycleEvents.java:10) ~[effortless-1.21-3.1.0.jar:?]
	at dev.huskuraft.effortless.fabric.platform.FabricInitializer.onInitialize(FabricInitializer.java:13) ~[effortless-1.21-3.1.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at dev.huskuraft.effortless.fabric.events.FabricEventRegistry.lambda$new$0(FabricEventRegistry.java:20) ~[effortless-1.21-3.1.0.jar:?]
	at dev.huskuraft.effortless.fabric.events.common.PlatformLifecycleEvents.lambda$static$0(PlatformLifecycleEvents.java:10) ~[effortless-1.21-3.1.0.jar:?]
	at dev.huskuraft.effortless.fabric.platform.FabricInitializer.onInitialize(FabricInitializer.java:13) ~[effortless-1.21-3.1.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more

**Comment by theaceofthespade** [comment]
I'm getting this error as well. I get it from both this one, and the forge version (which I believe are maintained by different people?)

**Comment by theaceofthespade** [comment]
It's worth noting I see this exact same error ": Could not execute entrypoint stage 'main' due to errors, provided by 'effortless'!" from A TON of mods, not just this one.

**Comment by d4w1kpl** [comment]
Really? I've actually never seen it on any mods, this is like the first one that did not work for me at all on a server.

**Comment by theaceofthespade** [comment]
Yeah it happens with a lot of ports - I believe I had the same issue with "fossilslegacy" - it's some sort of source version mismatching - maybe a server package build step, or some sort of dependency that's easily missed, but I know those aren't the only two mods I've seen it with.  Hopefully I'll get some time to help track it down.

**Comment by DirectorRen-TV** [comment]
I caught this one too on 1.21 fabric executable jar
all i have in mods folder: `effortless-1.21-3.1.0.jar` and `fabric-api-0.102.0+1.21.jar`

is there any workarounds?

**Comment by d4w1kpl** [comment]
> I caught this one too on 1.21 fabric executable jar all i have in mods folder: `effortless-1.21-3.1.0.jar` and `fabric-api-0.102.0+1.21.jar`
> 
> is there any workarounds? (Changing Fabric Loader to 0.16.0 and 0.15.11 had no effect at all)

i dont think there is one sadly. all we gotta do now is wait

**Comment by vinnyg0621** [comment]
it doesn't let me play with 1.21.1

**Comment by huskcasaca** [comment]
> it doesn't let me play with 1.21.1

No 1.21.1 has not been adapted to yet

**Comment by sukoshiotokonoko** [comment]
> > it doesn't let me play with 1.21.1
> 
> No 1.21.1 has not been adapted to yet

1.21.1 hasnt been officaly adapted but you can try changing the file so it boots with it and see if it works. it worked for me.

**Comment by popmullyxd** [comment]
some one got a fix?
