### ISSUE TITLE
[Fabric] Crash on server

### ISSUE THREAD

**Issue by Nevrai** [huskcasaca/effortless#180]
I can use the mod in single-player, but I’m unable to start a server with this mod.

### Fabric loader v0.16.0
```
[23:36:50] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'effortless'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.0.jar:?]
        at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.0.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21-loader.0.16.0-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
        at dev.huskuraft.effortless.fabric.events.FabricEventRegistry.lambda$new$0(FabricEventRegistry.java:20) ~[effortless-1.21-3.1.0.jar:?]
        at dev.huskuraft.effortless.fabric.events.common.PlatformLifecycleEvents.lambda$static$0(PlatformLifecycleEvents.java:10) ~[effortless-1.21-3.1.0.jar:?]
        at dev.huskuraft.effortless.fabric.platform.FabricInitializer.onInitialize(FabricInitializer.java:13) ~[effortless-1.21-3.1.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at dev.huskuraft.effortless.fabric.events.FabricEventRegistry.lambda$new$0(FabricEventRegistry.java:20) ~[effortless-1.21-3.1.0.jar:?]
        at dev.huskuraft.effortless.fabric.events.common.PlatformLifecycleEvents.lambda$static$0(PlatformLifecycleEvents.java:10) ~[effortless-1.21-3.1.0.jar:?]
        at dev.huskuraft.effortless.fabric.platform.FabricInitializer.onInitialize(FabricInitializer.java:13) ~[effortless-1.21-3.1.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
        ... 7 more
```

### Fabric loader v0.16.8
```
[23:56:48] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'effortless' at 'dev.huskuraft.effortless.fabric.platform.FabricInitializer'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.8.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.8.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.8.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.8.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.8.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.8.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21-loader.0.16.8-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
        at knot/dev.huskuraft.effortless.fabric.events.FabricEventRegistry.lambda$new$0(FabricEventRegistry.java:20) ~[effortless-1.21-3.1.0.jar:?]
        at knot/dev.huskuraft.effortless.fabric.events.common.PlatformLifecycleEvents.lambda$static$0(PlatformLifecycleEvents.java:10) ~[effortless-1.21-3.1.0.jar:?]
        at knot/dev.huskuraft.effortless.fabric.platform.FabricInitializer.onInitialize(FabricInitializer.java:13) ~[effortless-1.21-3.1.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.8.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.8.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/dev.huskuraft.effortless.fabric.events.FabricEventRegistry.lambda$new$0(FabricEventRegistry.java:20) ~[effortless-1.21-3.1.0.jar:?]
        at knot/dev.huskuraft.effortless.fabric.events.common.PlatformLifecycleEvents.lambda$static$0(PlatformLifecycleEvents.java:10) ~[effortless-1.21-3.1.0.jar:?]
        at knot/dev.huskuraft.effortless.fabric.platform.FabricInitializer.onInitialize(FabricInitializer.java:13) ~[effortless-1.21-3.1.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.8.jar:?]
        ... 7 more
```

## Versions
* **Minecraft**: 1.21
* **Modpack**: [Remade & Remastered: Tricks & Treats](https://modrinth.com/modpack/remade-remastered) (with 25 mods added)
* **Effortless Structure**: 3.1.0
* **Fabric**: 0.16.0, launcher 1.0.1 (_I also tried 0.16.8 but to no avail_)
* **Fabric API**: 0.100.7
* **Java**: 21.0.3.0 OpenJDK (_I also also tried Java 17 but to no avail_)

**Comment by popmullyxd** [comment]
hi i got the same issue. do u got a fix???
