### ISSUE TITLE
Game crash when placing dripstone

### ISSUE THREAD

**Issue by Rebilium** [huskcasaca/effortless#80]
game crashes when placing dripstone

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "this.reference" is null

crash report

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-03-21 22:18:30
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "this.reference" is null
	at dev.huskuraft.effortless.fabric.core.MinecraftBlockState.getItem(MinecraftBlockState.java:111)
	at dev.huskuraft.effortless.building.operation.block.BlockPlaceOperation.placeBlock(BlockPlaceOperation.java:67)
	at dev.huskuraft.effortless.building.operation.block.BlockPlaceOperation.commit(BlockPlaceOperation.java:111)
	at dev.huskuraft.effortless.building.operation.block.BlockPlaceOnClientOperation.commit(BlockPlaceOnClientOperation.java:31)
	at dev.huskuraft.effortless.building.operation.block.BlockPlaceOnClientOperation.commit(BlockPlaceOnClientOperation.java:16)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at dev.huskuraft.effortless.building.operation.batch.DeferredBatchOperation.commit(DeferredBatchOperation.java:24)
	at dev.huskuraft.effortless.EffortlessClientStructureBuilder.onClientTick(EffortlessClientStructureBuilder.java:286)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.huskuraft.effortless.api.events.EventFactory.invokeMethod(EventFactory.java:33)
	at dev.huskuraft.effortless.api.events.EventFactory$1.handleInvocation(EventFactory.java:42)
	at dev.huskuraft.effortless.api.events.EventFactory$AbstractInvocationHandler.invoke(EventFactory.java:222)
	at jdk.proxy2/jdk.proxy2.$Proxy56.onClientTick(Unknown Source)
	at dev.huskuraft.effortless.fabric.events.FabricClientEventRegistry.lambda$new$6(FabricClientEventRegistry.java:38)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$zoe000$fabric-lifecycle-events-v1$onStartTick(class_310.java:5772)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.huskuraft.effortless.fabric.core.MinecraftBlockState.getItem(MinecraftBlockState.java:111)
	at dev.huskuraft.effortless.building.operation.block.BlockPlaceOperation.placeBlock(BlockPlaceOperation.java:67)
	at dev.huskuraft.effortless.building.operation.block.BlockPlaceOperation.commit(BlockPlaceOperation.java:111)
	at dev.huskuraft.effortless.building.operation.block.BlockPlaceOnClientOperation.commit(BlockPlaceOnClientOperation.java:31)
	at dev.huskuraft.effortless.building.operation.block.BlockPlaceOnClientOperation.commit(BlockPlaceOnClientOperation.java:16)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at dev.huskuraft.effortless.building.operation.batch.DeferredBatchOperation.commit(DeferredBatchOperation.java:24)
	at dev.huskuraft.effortless.EffortlessClientStructureBuilder.onClientTick(EffortlessClientStructureBuilder.java:286)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.huskuraft.effortless.api.events.EventFactory.invokeMethod(EventFactory.java:33)
	at dev.huskuraft.effortless.api.events.EventFactory$1.handleInvocation(EventFactory.java:42)
	at dev.huskuraft.effortless.api.events.EventFactory$AbstractInvocationHandler.invoke(EventFactory.java:222)
	at jdk.proxy2/jdk.proxy2.$Proxy56.onClientTick(Unknown Source)
	at dev.huskuraft.effortless.fabric.events.FabricClientEventRegistry.lambda$new$6(FabricClientEventRegistry.java:38)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$zoe000$fabric-lifecycle-events-v1$onStartTick(class_310.java:5772)

-- Uptime --
Details:
	JVM uptime: 87.646s
	Wall uptime: 74.741s
	High-res time: 69.962s
	Client ticks: 980 ticks / 49.000s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Rebilium'/99, l='ClientLevel', x=-345.96, y=133.12, z=149.53]]
	Chunk stats: 1024, 533
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,111,0), Section: (at 0,15,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1234684 game time, 18000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 217

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, carpet, cloth-config, effortless, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, indium, itemscroller, jankson, jjelytraswap, lazydfu, libgui, librarian-trade-finder, litematica, lithium, malilib, minihud, modmenu, more_slabs_stairs_and_walls, music_control, no_fog, nvidium, reeses-sodium-options, sodium, starlight, tweakeroo, wi_zoom, worldedit, file/update_1_21_no_trial_chambers_1.20.4.zip, file/VanillaTweaks_r340085.zip

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 399175992 bytes (380 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: DriverVersion=26.20.100.7642
	Graphics card #1 name: NVIDIA GeForce GTX 1650 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f95
	Graphics card #1 versionInfo: DriverVersion=31.0.15.5186
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 17209.72
	Virtual memory used (MB): 12036.17
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 113.02
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Loaded Scarpet Apps: 
		reinforcement_zones
	Fabric Mods: 
		carpet: Carpet Mod 1.4.128+v231205
		effortless: Effortless 2.2.0
		fabric-api: Fabric API 0.96.1+1.20.4
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.49+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.13+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.1+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.1+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+44c0f8c64f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.74+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.23+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.7+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.63+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.11+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.18+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.53+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.0+d74054c14f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.56+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.0+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.18+b66dcf784f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.10+e84342304f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		indium: Indium 1.0.30+mc1.20.4
		itemscroller: Item Scroller 0.22.0
		java: OpenJDK 64-Bit Server VM 17
		jjelytraswap: Auto Elytra Swap 1.8
		lazydfu: LazyDFU 0.1.3
		librarian-trade-finder: Librarian Trade Finder 2.1.1
		litematica: Litematica 0.17.0
		lithium: Lithium 0.12.1
		malilib: MaLiLib 0.18.1
		minecraft: Minecraft 1.20.4
		minihud: MiniHUD 0.30.2
		modmenu: Mod Menu 9.0.0
		more_slabs_stairs_and_walls: More Slabs, Stairs & Walls 3.1.1
		music_control: Music Control 1.7.1+1.20.4
			cloth-config: Cloth Config v13 13.0.121
				cloth-basic-math: cloth-basic-math 0.6.1
			libgui: LibGui 9.2.1+1.20.2
				jankson: Jankson 6.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		no_fog: No Fog (NeoForge Version) 0.0.0+neoforge
		nvidium: Nvidium 0.2.6-beta
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.4-build.102
		shulkerplus: ShulkerPlus 1.0.7
		sodium: Sodium 0.5.8+mc1.20.4
		starlight: Starlight 1.1.3+fabric.f5dcd1a
		tweakeroo: Tweakeroo 0.19.2
		wi_zoom: WI Zoom 1.5-MC1.20.4
		worldedit: WorldEdit 7.3.0-beta-04+c28ebca
	Launched Version: fabric-loader-0.15.7-1.20.4
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.86, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Render Distance: 11/11 chunks
	Resource Packs: vanilla, fabric, file/update_1_21_no_trial_chambers_1.20.4.zip (incompatible), file/VanillaTweaks_r340085.zip
	Current Language: en_us
	Locale: en_US
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Rebilium'/99, l='ServerLevel[World1.20.4T]', x=-345.96, y=133.12, z=149.53]]
	Data Packs: vanilla, fabric, fabric-convention-tags-v1, more_slabs_stairs_and_walls, file/afk display v1.1.6 (MC 1.20-1.20.4).zip, file/anti enderman grief v1.1.6 (MC 1.20-1.20.4).zip, file/armor statues v2.8.11 (MC 1.20-1.20.4).zip, file/cave-cleaner-1.0.zip, file/VanillaTweaks_c851075_MC1.20-1.20.4.zip, file/double shulker shells v1.3.6 (MC 1.20-1.20.4).zip, file/durability ping v1.1.6 (MC 1.20-1.20.4).zip, file/nether portal coords v1.1.6 (MC 1.20-1.20.4).zip, file/silence mobs v1.2.1 (MC 1.20-1.20.4).zip, file/spectator conduit power v1.1.6 (MC 1.20-1.20.4).zip, file/spectator night vision v1.1.6 (MC 1.20-1.20.4).zip, file/update_1_21_no_trial_chambers_1.20.4.zip, file/wandering trades v1.7.3 (MC 1.20-1.20.4).zip
	Enabled Feature Flags: minecraft:update_1_21, minecraft:vanilla
	World Generation: Stable

**Comment by Rebilium** [comment]
Edit: if done fast, sometimes it won't crash, pluse placing drippstone on fhe floor works fine it happens only if placed under. Also looking at the sky while holding the drippstone while trying to place it, makes the game instantly crash
